name: Build & Publish

on:
  push:
    branches: [ main, master ]
    tags: [ v* ]

env:
  buildConfiguration: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: 5.x

    - name: Execute GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.13
      id: gitversion
      with:
        additionalArguments: /output BuildServer
        useConfigFile: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c ${{ env.buildConfiguration }} --no-restore -p:Version=$NUGETVER -p:FileVersion=$SEMVER -p:AssemblyVersion=$ASSEMBLYVER
      env:
        NUGETVER: ${{ steps.gitversion.outputs.nuGetVersion }}
        SEMVER: ${{ steps.gitversion.outputs.assemblySemFileVer }}
        ASSEMBLYVER: 1.0.0.0

    - name: Test
      run: dotnet test -c ${{ env.buildConfiguration }} --no-build -v normal --filter FullyQualifiedName!~IntegrationTests

    - name: Pack
      run: dotnet pack -c ${{ env.buildConfiguration }} -o "${{ github.workspace }}/artifacts/" -p:PackageVersion=$NUGETVER
      env:
        NUGETVER: ${{ steps.gitversion.outputs.nuGetVersion }}

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: |
          ${{ github.workspace }}/artifacts/*.nupkg
          ${{ github.workspace }}/artifacts/*.snupkg

    - name: Push (Pre-release)
      if: ${{ steps.gitversion.outputs.nuGetPreReleaseTag != '' }}
      run: dotnet nuget push "${{ github.workspace }}/artifacts/*.nupkg" -s $NUGET_SOURCE -k $NUGET_API_KEY --skip-duplicate
      env:
        NUGET_SOURCE: ${{ secrets.MYGET_SOURCE }}
        NUGET_API_KEY: ${{ secrets.MYGET_API_KEY }}

    - name: Push (Release)
      if: ${{ steps.gitversion.outputs.nuGetPreReleaseTag == '' }}
      run: dotnet nuget push "${{ github.workspace }}/artifacts/*.nupkg" -s $NUGET_SOURCE -k $NUGET_API_KEY --skip-duplicate
      env:
        NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
